// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.15.6
// source: pusher.proto

package pusher_rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Op int32

const (
	Op_INIT  Op = 0
	Op_SUB   Op = 2
	Op_UNSUB Op = 3
)

// Enum value maps for Op.
var (
	Op_name = map[int32]string{
		0: "INIT",
		2: "SUB",
		3: "UNSUB",
	}
	Op_value = map[string]int32{
		"INIT":  0,
		"SUB":   2,
		"UNSUB": 3,
	}
)

func (x Op) Enum() *Op {
	p := new(Op)
	*p = x
	return p
}

func (x Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Op) Descriptor() protoreflect.EnumDescriptor {
	return file_pusher_proto_enumTypes[0].Descriptor()
}

func (Op) Type() protoreflect.EnumType {
	return &file_pusher_proto_enumTypes[0]
}

func (x Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Op.Descriptor instead.
func (Op) EnumDescriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{0}
}

type RealTimeQuoteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Op     Op     `protobuf:"varint,1,opt,name=op,proto3,enum=pusher.Op" json:"op,omitempty"`
	UserId uint32 `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	Ids    []*Id  `protobuf:"bytes,3,rep,name=ids,proto3" json:"ids,omitempty"`
}

func (x *RealTimeQuoteRequest) Reset() {
	*x = RealTimeQuoteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pusher_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealTimeQuoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealTimeQuoteRequest) ProtoMessage() {}

func (x *RealTimeQuoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pusher_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealTimeQuoteRequest.ProtoReflect.Descriptor instead.
func (*RealTimeQuoteRequest) Descriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{0}
}

func (x *RealTimeQuoteRequest) GetOp() Op {
	if x != nil {
		return x.Op
	}
	return Op_INIT
}

func (x *RealTimeQuoteRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RealTimeQuoteRequest) GetIds() []*Id {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Id struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Exchange uint32 `protobuf:"varint,1,opt,name=Exchange,proto3" json:"Exchange,omitempty"`
	Code     string `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
}

func (x *Id) Reset() {
	*x = Id{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pusher_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Id) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Id) ProtoMessage() {}

func (x *Id) ProtoReflect() protoreflect.Message {
	mi := &file_pusher_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Id.ProtoReflect.Descriptor instead.
func (*Id) Descriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{1}
}

func (x *Id) GetExchange() uint32 {
	if x != nil {
		return x.Exchange
	}
	return 0
}

func (x *Id) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type Quote struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   *Id    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=Data,proto3" json:"Data,omitempty"`
}

func (x *Quote) Reset() {
	*x = Quote{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pusher_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Quote) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Quote) ProtoMessage() {}

func (x *Quote) ProtoReflect() protoreflect.Message {
	mi := &file_pusher_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Quote.ProtoReflect.Descriptor instead.
func (*Quote) Descriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{2}
}

func (x *Quote) GetId() *Id {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Quote) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type RealTimeQuoteResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Quote []*Quote `protobuf:"bytes,1,rep,name=quote,proto3" json:"quote,omitempty"`
}

func (x *RealTimeQuoteResp) Reset() {
	*x = RealTimeQuoteResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pusher_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RealTimeQuoteResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealTimeQuoteResp) ProtoMessage() {}

func (x *RealTimeQuoteResp) ProtoReflect() protoreflect.Message {
	mi := &file_pusher_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealTimeQuoteResp.ProtoReflect.Descriptor instead.
func (*RealTimeQuoteResp) Descriptor() ([]byte, []int) {
	return file_pusher_proto_rawDescGZIP(), []int{3}
}

func (x *RealTimeQuoteResp) GetQuote() []*Quote {
	if x != nil {
		return x.Quote
	}
	return nil
}

var File_pusher_proto protoreflect.FileDescriptor

var file_pusher_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x22, 0x68, 0x0a, 0x14, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69,
	0x6d, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a,
	0x0a, 0x02, 0x6f, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0a, 0x2e, 0x70, 0x75, 0x73,
	0x68, 0x65, 0x72, 0x2e, 0x4f, 0x70, 0x52, 0x02, 0x6f, 0x70, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1c, 0x0a, 0x03, 0x69, 0x64, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0a, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x49, 0x64, 0x52, 0x03, 0x69, 0x64, 0x73,
	0x22, 0x34, 0x0a, 0x02, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x45, 0x78, 0x63, 0x68, 0x61, 0x6e,
	0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x37, 0x0a, 0x05, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12,
	0x1a, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x70, 0x75,
	0x73, 0x68, 0x65, 0x72, 0x2e, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x44,
	0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x38, 0x0a, 0x11, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e, 0x51, 0x75, 0x6f,
	0x74, 0x65, 0x52, 0x05, 0x71, 0x75, 0x6f, 0x74, 0x65, 0x2a, 0x22, 0x0a, 0x02, 0x4f, 0x70, 0x12,
	0x08, 0x0a, 0x04, 0x49, 0x4e, 0x49, 0x54, 0x10, 0x00, 0x12, 0x07, 0x0a, 0x03, 0x53, 0x55, 0x42,
	0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x55, 0x4e, 0x53, 0x55, 0x42, 0x10, 0x03, 0x32, 0x58, 0x0a,
	0x06, 0x50, 0x75, 0x73, 0x68, 0x65, 0x72, 0x12, 0x4e, 0x0a, 0x0d, 0x52, 0x65, 0x61, 0x6c, 0x54,
	0x69, 0x6d, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x12, 0x1c, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x65,
	0x72, 0x2e, 0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x70, 0x75, 0x73, 0x68, 0x65, 0x72, 0x2e,
	0x52, 0x65, 0x61, 0x6c, 0x54, 0x69, 0x6d, 0x65, 0x51, 0x75, 0x6f, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x0d, 0x5a, 0x0b, 0x2f, 0x70, 0x75, 0x73, 0x68,
	0x65, 0x72, 0x5f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pusher_proto_rawDescOnce sync.Once
	file_pusher_proto_rawDescData = file_pusher_proto_rawDesc
)

func file_pusher_proto_rawDescGZIP() []byte {
	file_pusher_proto_rawDescOnce.Do(func() {
		file_pusher_proto_rawDescData = protoimpl.X.CompressGZIP(file_pusher_proto_rawDescData)
	})
	return file_pusher_proto_rawDescData
}

var file_pusher_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pusher_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pusher_proto_goTypes = []interface{}{
	(Op)(0),                      // 0: pusher.Op
	(*RealTimeQuoteRequest)(nil), // 1: pusher.RealTimeQuoteRequest
	(*Id)(nil),                   // 2: pusher.Id
	(*Quote)(nil),                // 3: pusher.Quote
	(*RealTimeQuoteResp)(nil),    // 4: pusher.RealTimeQuoteResp
}
var file_pusher_proto_depIdxs = []int32{
	0, // 0: pusher.RealTimeQuoteRequest.op:type_name -> pusher.Op
	2, // 1: pusher.RealTimeQuoteRequest.ids:type_name -> pusher.Id
	2, // 2: pusher.Quote.id:type_name -> pusher.Id
	3, // 3: pusher.RealTimeQuoteResp.quote:type_name -> pusher.Quote
	1, // 4: pusher.Pusher.RealTimeQuote:input_type -> pusher.RealTimeQuoteRequest
	4, // 5: pusher.Pusher.RealTimeQuote:output_type -> pusher.RealTimeQuoteResp
	5, // [5:6] is the sub-list for method output_type
	4, // [4:5] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pusher_proto_init() }
func file_pusher_proto_init() {
	if File_pusher_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pusher_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealTimeQuoteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pusher_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Id); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pusher_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Quote); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pusher_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RealTimeQuoteResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pusher_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pusher_proto_goTypes,
		DependencyIndexes: file_pusher_proto_depIdxs,
		EnumInfos:         file_pusher_proto_enumTypes,
		MessageInfos:      file_pusher_proto_msgTypes,
	}.Build()
	File_pusher_proto = out.File
	file_pusher_proto_rawDesc = nil
	file_pusher_proto_goTypes = nil
	file_pusher_proto_depIdxs = nil
}
